services:
  - type: web
    name: go-name-generator
    env: go
    region: oregon # Choose the appropriate region
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    healthCheckPath: /stats
    autoDeploy: true
    numInstances: 1 # Scale this up for more concurrency
    plan: starter # Choose appropriate plan: starter, starter-plus, standard, etc.
    envVars:
      - key: PORT
        value: 10000 # Render assigns a port for your service
      - key: GO_ENV
        value: production
    
